services:
  mock-mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mock_db
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"

  tests:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    environment:
      DB_NAME: mock_db
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: docker.host.internal
      DB_PORT: 3306
    command: python -m pytest -vv -s

  local-tests:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    environment:
      DB_NAME: mock_db
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: docker.host.internal # same as tests but with a different host
      DB_PORT: 3306
    command: python -m pytest -vv -s

