services:
  mock-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: mock_db
    ports:
      - "3306:3306"

  tests:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    environment:
      DB_COMPANY_SCANNER: test_database
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    command: python -m pytest -vv -s
