services:
  mock-mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mock_db
      MYSQL_USER: test
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "test", "-p", "test" ]


  tests:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    environment:
      DB_NAME: mock_db
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    depends_on:
      - mock-mysql
    command: python -m pytest -vv -s

