name: Integration Tests

on: pull_request

jobs:
  pytests:
    runs-on: ubuntu-latest

    services:
      mock-mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: mock_db
          MYSQL_USER: test
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements-dev.txt
      - run: coverage run --source=src -m pytest -vv
        env:
         LOG_LEVEL: DEBUG
         DB_NAME: mock_db
         DB_USER: test
         DB_PASSWORD: test
         DB_HOST: mock-mysql
         DB_PORT: 3306
      - run: coverage report -m



##        env:
##          DB_HOST: mock-mysql  # Use the service name defined in docker-compose.yml
##          DB_PORT: 3306
##          DB_USER: test
##          DB_PASSWORD: test
##          DB_DATABASE: mock_db
#
#      - name: Stop and clean up containers
#        run: |
#          docker-compose down
